In [24]:
import seaborn as sns
import numpy as np
import pandas as pd

In [25]:
import seaborn as sns

df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [26]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [27]:
df = df.drop(columns=['deck'])

In [28]:
df.bfill(inplace= True).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [29]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [30]:
df.shape

(891, 14)

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     891 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  embark_town  891 non-null    str
 12  alive        891 non-null    str
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), str(5)
memory usage: 99.0 KB

In [32]:
df.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [35]:
df = df.drop(columns=['alive', 'alone', 'embarked', 'class', 'adult_male', 'who'], errors='ignore')

In [36]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare  embark_town
0         0       3    male  22.0      1      0   7.2500  Southampton
1         1       1  female  38.0      1      0  71.2833    Cherbourg
2         1       3  female  26.0      0      0   7.9250  Southampton
3         1       1  female  35.0      1      0  53.1000  Southampton
4         0       3    male  35.0      0      0   8.0500  Southampton

In [37]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False)
encoded_cols = ohe.fit_transform(df[['sex', 'embark_town']])

In [41]:
# 1. Encoded features ka ek naya DataFrame banayein
encoded_df = pd.DataFrame(
    encoded_cols,
    columns=ohe.get_feature_names_out(['sex', 'embark_town'])
)

# 2. Purane text columns ko hatakar naye encoded columns merge karein
df = df.drop(columns=['sex', 'embark_town']).reset_index(drop=True)
df = pd.concat([df, encoded_df], axis=1)

df.head()

,survived,pclass,age,sibsp,parch,fare,sex_male,embark_town_Queenstown,embark_town_Southampton
0,0,3,22.0,1,0,7.2500,1.0,0.0,1.0
1,1,1,38.0,1,0,71.2833,0.0,0.0,0.0
2,1,3,26.0,0,0,7.9250,0.0,0.0,1.0
3,1,1,35.0,1,0,53.1000,0.0,0.0,1.0
4,0,3,35.0,0,0,8.0500,1.0,0.0,1.0

In [42]:
from sklearn.preprocessing import MinMaxScaler

min_max = MinMaxScaler()

num_cols = ['age', 'fare']
df[num_cols] = min_max.fit_transform(df[num_cols])

df.head()

,survived,pclass,age,sibsp,parch,fare,sex_male,embark_town_Queenstown,embark_town_Southampton
0,0,3,0.271174,1,0,0.014151,1.0,0.0,1.0
1,1,1,0.472229,1,0,0.139136,0.0,0.0,0.0
2,1,3,0.321438,0,0,0.015469,0.0,0.0,1.0
3,1,1,0.434531,1,0,0.103644,0.0,0.0,1.0
4,0,3,0.434531,0,0,0.015713,1.0,0.0,1.0

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop(columns=['survived'])
y = df['survived']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Data leakage se bachne ke liye scaler ko sirf train data par fit karte hain
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [44]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
print(f"Random Forest Accuracy: {rf.score(X_test, y_test) * 100:.2f}%")

Random Forest Accuracy: 82.68%