In [30]:
import numpy as np
import pandas as pd
df = pd.read_csv(r"C:\Users\dell\Downloads\movies_data.csv")

In [31]:
df.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,#Gadhvi (He thought he was Gandhi),2019,109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
1,#Yaaram,2019,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
2,...Aur Pyaar Ho Gaya,1997,147,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
3,...Yahaan,2005,142,"Drama, Romance, War",7.4,1086,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
4,?: A Question Mark,2012,82,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia

In [32]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
transactions = df['Genre'].dropna().str.split(r'\s*,\s*').tolist()
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df_encoded = pd.DataFrame(te_ary, columns=te.columns_)

In [33]:
df_encoded.head()

,Action,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,Fantasy,...,Music,Musical,Mystery,News,Romance,Sci-Fi,Sport,Thriller,War,Western
0,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,True,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,True,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,True,False,False

In [34]:
frequent_itemsets = apriori(df_encoded, min_support=0.05, use_colnames=True)

# Step 4: Association Rules generate karein (min_confidence = 30%)
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.3)

# Step 5: Top rules ko Lift ke hisab se sort karke dekhein
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,support,confidence,lift
9,"frozenset({Action, Drama})",frozenset({Crime}),0.058844,0.335347,2.168836
10,frozenset({Crime}),"frozenset({Action, Drama})",0.058844,0.380571,2.168836
1,frozenset({Action}),frozenset({Crime}),0.090299,0.303084,1.960176
0,frozenset({Crime}),frozenset({Action}),0.090299,0.584000,1.960176
8,"frozenset({Crime, Drama})",frozenset({Action}),0.058844,0.568259,1.907343
5,frozenset({Family}),frozenset({Drama}),0.058844,0.800481,1.193341
4,frozenset({Crime}),frozenset({Drama}),0.103552,0.669714,0.998397
7,"frozenset({Crime, Action})",frozenset({Drama}),0.058844,0.651663,0.971487
6,frozenset({Romance}),frozenset({Drama}),0.158332,0.649275,0.967927
2,frozenset({Action}),frozenset({Drama}),0.175473,0.588968,0.878022

In [35]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

# 1. Genre column ke comma-separated values ko list me convert karein
# Missing values hatakar har row ko list of items banayein
transactionstransactions = df['Genre'].dropna().apply(lambda x: [item.strip() for item in x.split(',')]).tolist()

# 2. TransactionEncoder apply karein
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df_encoded = pd.DataFrame(te_ary, columns=te.columns_)

# 3. Frequent itemsets generate karein
frequent_itemsets = apriori(df_encoded, min_support=0.02, use_colnames=True)

# 4. Association Rules generate karein (agar rules na banein to min_threshold thoda kam kar sakte hain)
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.2)

# 5. Top rules display karein
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,support,confidence,lift
23,frozenset({Crime}),"frozenset({Action, Drama})",0.058844,0.380571,2.168836
22,"frozenset({Action, Drama})",frozenset({Crime}),0.058844,0.335347,2.168836
0,frozenset({Adventure}),frozenset({Action}),0.028980,0.592058,1.987221
3,frozenset({Action}),frozenset({Crime}),0.090299,0.303084,1.960176
2,frozenset({Crime}),frozenset({Action}),0.090299,0.584000,1.960176
18,frozenset({Musical}),frozenset({Romance}),0.034105,0.468447,1.920971
21,"frozenset({Crime, Drama})",frozenset({Action}),0.058844,0.568259,1.907343
11,frozenset({Thriller}),frozenset({Crime}),0.025800,0.215022,1.390640
12,frozenset({Family}),frozenset({Drama}),0.058844,0.800481,1.193341
9,frozenset({Romance}),frozenset({Comedy}),0.065383,0.268116,1.128920

In [36]:
transactions

[['Drama'],
 ['Comedy', 'Romance'],
 ['Comedy', 'Drama', 'Musical'],
 ['Drama', 'Romance', 'War'],
 ['Horror', 'Mystery', 'Thriller'],
 ['Action', 'Crime', 'Thriller'],
 ['Drama'],
 ['Horror'],
 ['Horror', 'Romance', 'Thriller'],
 ['Comedy', 'Drama', 'Romance'],
 ['Comedy', 'Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Crime', 'Drama', 'Mystery'],
 ['Horror', 'Thriller'],
 ['Comedy', 'Horror'],
 ['Drama', 'Horror', 'Mystery'],
 ['Drama'],
 ['Drama'],
 ['Action', 'Thriller'],
 ['Action'],
 ['Drama'],
 ['Horror', 'Mystery', 'Romance'],
 ['Horror', 'Mystery'],
 ['Drama', 'Horror', 'Romance'],
 ['Horror', 'Mystery', 'Romance'],
 ['Action', 'Drama', 'History'],
 ['Action', 'Drama', 'War'],
 ['Thriller'],
 ['Comedy'],
 ['Adventure', 'Horror', 'Mystery'],
 ['Action', 'Crime', 'Thriller'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Sci-Fi'],
 ['Crime', 'Mystery', 'Thriller'],
 ['Comedy'],
 ['Thriller'],
 ['Drama', 'History'],
 ['Sport'],
 ['Biography', 'Drama', 'History'],
 ['Drama'],
 ['Horror', 'Romance'],
 ['Comedy', 'Romance'],
 ['Crime', 'Drama'],
 ['Comedy'],
 ['Comedy', 'Drama'],
 ['Drama'],
 ['Adventure', 'Drama'],
 ['Action', 'Drama', 'History'],
 ['Comedy', 'Mystery', 'Thriller'],
 ['Drama', 'Romance'],
 ['Crime', 'Thriller'],
 ['Drama'],
 ['Horror'],
 ['Horror', 'Sci-Fi', 'Thriller'],
 ['Horror'],
 ['Drama', 'Mystery', 'Thriller'],
 ['Drama'],
 ['Drama', 'Family', 'Musical'],
 ['Thriller'],
 ['Action', 'Comedy'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Horror'],
 ['Drama'],
 ['Comedy', 'Drama'],
 ['Action'],
 ['Crime', 'Thriller'],
 ['Documentary'],
 ['Drama', 'Mystery', 'Thriller'],
 ['Drama', 'Horror', 'Musical'],
 ['Thriller'],
 ['Action', 'Biography', 'Drama'],
 ['Action', 'Fantasy', 'Mystery'],
 ['Adventure', 'Drama', 'Mystery'],
 ['Mystery', 'Thriller'],
 ['Action'],
 ['Comedy', 'Crime', 'Drama'],
 ['Musical', 'Romance'],
 ['Crime', 'Drama'],
 ['Drama'],
 ['Drama'],
 ['Drama', 'Thriller'],
 ['Horror', 'Mystery'],
 ['Drama', 'Horror', 'Romance'],
 ['Action', 'Adventure', 'Comedy'],
 ['Comedy', 'Romance'],
 ['Action', 'Comedy'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Romance'],
 ['Thriller'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Musical', 'Romance', 'Drama'],
 ['Drama'],
 ['Action', 'Sci-Fi', 'Thriller'],
 ['Action', 'Drama', 'Romance'],
 ['Mystery', 'Romance'],
 ['Action'],
 ['Drama'],
 ['Fantasy'],
 ['Comedy', 'Crime', 'Drama'],
 ['Horror'],
 ['Action', 'Crime', 'Drama'],
 ['Action'],
 ['Drama'],
 ['Drama'],
 ['Action', 'Crime', 'Thriller'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Action', 'Crime', 'Drama'],
 ['Fantasy'],
 ['Drama', 'Romance', 'Thriller'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Drama', 'Family'],
 ['Horror'],
 ['Crime', 'Drama'],
 ['Musical', 'Romance'],
 ['Action', 'Comedy', 'Drama'],
 ['Action'],
 ['Action'],
 ['Action', 'Drama'],
 ['Action'],
 ['Action', 'Thriller'],
 ['Action'],
 ['Horror'],
 ['Comedy', 'Crime', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Action', 'Drama'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Drama'],
 ['Drama', 'Romance'],
 ['Action'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Drama'],
 ['Action', 'Thriller'],
 ['Action', 'Romance'],
 ['Action', 'Crime'],
 ['Action', 'Romance'],
 ['Action', 'Drama'],
 ['Action', 'Drama'],
 ['Action'],
 ['Action', 'Drama', 'Crime'],
 ['Romance'],
 ['Drama', 'Family', 'Music'],
 ['Drama', 'Romance'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Thriller'],
 ['Action', 'Drama', 'Family'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Thriller'],
 ['Drama'],
 ['Action', 'Romance'],
 ['Action'],
 ['Drama', 'History', 'Romance'],
 ['Crime', 'Drama', 'Music'],
 ['Action', 'Crime', 'Thriller'],
 ['Sci-Fi'],
 ['Action', 'Thriller'],
 ['Action'],
 ['Drama', 'Family'],
 ['Comedy', 'Drama', 'Family'],
 ['Action', 'Crime', 'Drama'],
 ['Crime', 'Mystery', 'Romance'],
 ['Action', 'Crime', 'Drama'],
 ['Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Action', 'Crime', 'Drama'],
 ['Drama'],
 ['Action', 'Drama', 'Family'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Drama'],
 ['Drama'],
 ['Drama'],
 ['Action', 'Comedy', 'Crime'],
 ['Crime', 'Drama', 'Thriller'],
 ['Drama', 'Romance'],
 ['Comedy', 'Drama', 'Family'],
 ['Romance'],
 ['Comedy', 'Family', 'Fantasy'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama', 'Family'],
 ['Romance', 'Drama'],
 ['Action', 'Comedy', 'Drama'],
 ['Comedy', 'Romance'],
 ['Drama', 'Family', 'Romance'],
 ['Action', 'Drama', 'Romance'],
 ['Romance', 'Drama', 'Family'],
 ['Action', 'Romance'],
 ['Action', 'Comedy', 'Drama'],
 ['Action'],
 ['Thriller'],
 ['Drama', 'Thriller'],
 ['Drama'],
 ['Musical', 'Romance', 'Thriller'],
 ['Family', 'Musical', 'Romance'],
 ['Action', 'Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Comedy', 'Romance'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama'],
 ['Romance'],
 ['Action', 'Drama', 'Romance'],
 ['Drama', 'Romance', 'Thriller'],
 ['Romance'],
 ['Musical', 'Drama', 'Romance'],
 ['Drama', 'Music', 'Musical'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Drama'],
 ['Drama', 'Mystery'],
 ['Drama'],
 ['Adventure', 'Comedy', 'Romance'],
 ['Action'],
 ['Drama', 'Family'],
 ['Drama'],
 ['Action', 'Thriller'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Drama', 'Thriller'],
 ['Action'],
 ['Action', 'Crime', 'Drama'],
 ['Crime', 'Drama', 'Horror'],
 ['Drama', 'Horror', 'Thriller'],
 ['Comedy', 'Romance'],
 ['Drama', 'Romance'],
 ['Romance'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Action'],
 ['Musical', 'Romance'],
 ['Action', 'Musical', 'Thriller'],
 ['Action', 'Drama', 'Romance'],
 ['Comedy'],
 ['Drama'],
 ['Comedy'],
 ['Action', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Crime', 'Thriller'],
 ['Drama', 'Romance'],
 ['Action', 'Drama', 'War'],
 ['Romance', 'Thriller'],
 ['Drama', 'Music'],
 ['Action', 'Drama', 'Romance'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Fantasy'],
 ['Action', 'Drama', 'Thriller'],
 ['Drama', 'Romance'],
 ['Drama', 'Musical'],
 ['Crime', 'Drama', 'Musical'],
 ['Action', 'Comedy', 'Drama'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Crime', 'Drama', 'Thriller'],
 ['Crime', 'Drama'],
 ['Action', 'Mystery', 'Thriller'],
 ['Drama', 'Musical', 'Romance'],
 ['Action', 'Crime', 'Mystery'],
 ['Action', 'Adventure', 'Thriller'],
 ['Action', 'Crime', 'Thriller'],
 ['Comedy', 'Romance', 'Sci-Fi'],
 ['Action', 'Crime', 'Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Action', 'Drama', 'Family'],
 ['Action', 'Drama', 'Mystery'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Drama'],
 ['Drama'],
 ['Action', 'Comedy', 'Thriller'],
 ['Biography', 'Drama'],
 ['Drama'],
 ['Action', 'Comedy', 'Fantasy'],
 ['Drama', 'Family', 'Horror'],
 ['Drama'],
 ['Adventure'],
 ['Adventure'],
 ['Action', 'Adventure', 'Family'],
 ['Action', 'Adventure', 'Comedy'],
 ['Drama', 'Music', 'Musical'],
 ['Action', 'Drama', 'Musical'],
 ['Action', 'Comedy', 'Crime'],
 ['Adventure', 'Thriller'],
 ['Drama', 'Romance'],
 ['Drama', 'Family'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Comedy', 'Romance'],
 ['Crime', 'Mystery'],
 ['Drama', 'Family'],
 ['Adventure', 'Comedy', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Adventure', 'Thriller'],
 ['Drama', 'Crime'],
 ['Action', 'Drama', 'Romance'],
 ['Action'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action'],
 ['Crime', 'Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Action'],
 ['Action'],
 ['Drama', 'Fantasy', 'Romance'],
 ['Musical', 'Comedy', 'Drama'],
 ['Drama', 'Horror', 'Mystery'],
 ['Comedy', 'Drama'],
 ['Drama'],
 ['Action', 'Drama'],
 ['Musical', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama', 'History'],
 ['Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Comedy', 'Romance'],
 ['Action', 'Comedy', 'Drama'],
 ['Romance', 'Thriller'],
 ['Drama', 'Romance', 'Thriller'],
 ['Action', 'Drama', 'Thriller'],
 ['Comedy', 'Romance'],
 ['Comedy', 'Romance'],
 ['Action', 'Comedy', 'Romance'],
 ['Drama'],
 ['Drama', 'Romance'],
 ['Action', 'Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Adventure', 'Comedy'],
 ['Action', 'Thriller'],
 ['Action', 'Comedy', 'Crime'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Action', 'Drama', 'Thriller'],
 ['Drama', 'History', 'Musical'],
 ['Thriller'],
 ['Drama'],
 ['Romance'],
 ['Comedy', 'Romance'],
 ['Action', 'Drama'],
 ['Action', 'Crime', 'Horror'],
 ['Drama', 'Romance', 'Thriller'],
 ['Crime', 'Drama', 'Mystery'],
 ['Drama', 'Musical'],
 ['Adventure', 'Fantasy'],
 ['Action', 'Adventure', 'Comedy'],
 ['Family', 'Musical', 'Romance'],
 ['Action', 'Drama', 'Fantasy'],
 ['Comedy'],
 ['Drama'],
 ['Adventure', 'Drama', 'Fantasy'],
 ['Comedy', 'Drama', 'Romance'],
 ['Comedy', 'Drama', 'Musical'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama'],
 ['Drama'],
 ['Adventure', 'Fantasy', 'Romance'],
 ['Action', 'Adventure', 'Drama'],
 ['Action', 'Adventure'],
 ['Drama'],
 ['Fantasy'],
 ['Biography', 'Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Thriller'],
 ['Action', 'Drama'],
 ['Action', 'Comedy', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Comedy'],
 ['Action', 'Drama'],
 ['Horror'],
 ['Comedy', 'Crime', 'Drama'],
 ['Action', 'Drama'],
 ['Adventure', 'Drama', 'Romance'],
 ['Action'],
 ['Drama', 'Family'],
 ['Drama', 'Musical', 'Romance'],
 ['Musical', 'Romance'],
 ['Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama'],
 ['Drama'],
 ['Action', 'Adventure', 'Comedy'],
 ['Action', 'Comedy', 'Drama'],
 ['Horror', 'Thriller'],
 ['Family'],
 ['Action', 'Adventure', 'Drama'],
 ['Mystery'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Thriller'],
 ['Family'],
 ['Comedy', 'Romance'],
 ['Drama'],
 ['Drama', 'Fantasy', 'Thriller'],
 ['Comedy', 'Drama'],
 ['Musical', 'Fantasy'],
 ['Drama', 'Family'],
 ['Drama'],
 ['Musical', 'Romance', 'Thriller'],
 ['Documentary', 'Thriller'],
 ['Drama'],
 ['Mystery', 'Romance', 'Musical'],
 ['Drama', 'Musical'],
 ['Biography', 'Drama', 'History'],
 ['Drama', 'Family'],
 ['Comedy', 'Drama', 'Musical'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Comedy'],
 ['History', 'Musical', 'Romance'],
 ['Crime', 'Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Musical', 'Drama', 'Crime'],
 ['Drama', 'Romance'],
 ['Action', 'Comedy', 'Drama'],
 ['Action', 'Comedy', 'Romance'],
 ['Action', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Drama'],
 ['Crime', 'Drama', 'Music'],
 ['Crime', 'Drama', 'Thriller'],
 ['Comedy', 'Drama'],
 ['Drama', 'Thriller'],
 ['Action', 'Comedy', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Crime'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Drama'],
 ['Comedy'],
 ['Drama'],
 ['Action', 'Romance'],
 ['Comedy', 'Drama'],
 ['Comedy', 'Drama'],
 ['Action', 'Adventure', 'Drama'],
 ['Drama', 'Romance', 'Thriller'],
 ['Drama', 'Romance', 'Thriller'],
 ['Musical', 'Thriller', 'Mystery'],
 ['Thriller'],
 ['Drama', 'Thriller'],
 ['Romance'],
 ['Comedy', 'Drama', 'Musical'],
 ['Horror'],
 ['Action', 'Comedy', 'Crime'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Comedy', 'Crime'],
 ['Drama'],
 ['Biography', 'Drama', 'Romance'],
 ['Action', 'Adventure', 'Drama'],
 ['Comedy', 'Drama'],
 ['Romance'],
 ['Drama', 'Thriller'],
 ['Drama'],
 ['Action', 'Drama'],
 ['Drama', 'Family', 'Romance'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama'],
 ['Drama', 'Family'],
 ['Biography'],
 ['Drama'],
 ['Action', 'Drama'],
 ['Action', 'Comedy', 'Crime'],
 ['Comedy'],
 ['Drama'],
 ['Drama'],
 ['Drama', 'Family'],
 ['History'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama', 'Romance'],
 ['Crime', 'Drama', 'Mystery'],
 ['Drama', 'Musical', 'Romance'],
 ['Crime', 'Drama', 'Thriller'],
 ['Drama', 'Family'],
 ['Crime', 'Drama'],
 ['Drama'],
 ['Drama'],
 ['Action'],
 ['Mystery', 'Thriller'],
 ['Drama'],
 ['Crime'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama', 'Family'],
 ['Drama', 'Romance', 'Thriller'],
 ['Biography', 'Drama', 'Music'],
 ['Action'],
 ['Action', 'Crime', 'Drama'],
 ['Drama', 'Mystery', 'Thriller'],
 ['Drama', 'Sci-Fi'],
 ['Comedy'],
 ['Comedy', 'Musical', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama', 'Sport'],
 ['Action', 'Drama'],
 ['Crime', 'Drama', 'Mystery'],
 ['Drama', 'Family', 'Comedy'],
 ['Drama', 'Romance'],
 ['Action', 'Thriller', 'Romance'],
 ['Drama'],
 ['Mystery'],
 ['Comedy', 'Romance', 'Thriller'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama'],
 ['Crime', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Crime', 'Musical'],
 ['Action', 'Crime', 'Romance'],
 ['Action', 'Comedy'],
 ['Animation', 'Action', 'Adventure'],
 ['Drama', 'Family'],
 ['Drama', 'Family', 'Romance'],
 ['Action', 'Drama'],
 ['Drama', 'Family', 'Music'],
 ['Comedy', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Crime', 'Drama', 'Mystery'],
 ['Drama'],
 ['Action', 'Drama'],
 ['Action', 'Drama', 'Sport'],
 ['Musical', 'Romance'],
 ['Drama', 'Musical', 'Romance'],
 ['Action', 'Adventure', 'Drama'],
 ['Documentary', 'History'],
 ['Drama', 'Romance'],
 ['Drama', 'Family', 'Romance'],
 ['Action', 'Thriller'],
 ['Drama', 'Romance'],
 ['Thriller'],
 ['Action'],
 ['Drama'],
 ['Action', 'Biography', 'Drama'],
 ['Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama'],
 ['Family'],
 ['Comedy', 'Musical'],
 ['Drama'],
 ['Thriller'],
 ['Action', 'Adventure', 'Comedy'],
 ['Action'],
 ['Crime', 'Drama'],
 ['Drama', 'Romance'],
 ['Comedy'],
 ['Comedy'],
 ['Drama', 'Musical'],
 ['Biography', 'Crime', 'Thriller'],
 ['Comedy', 'Drama'],
 ['Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Horror', 'Mystery', 'Thriller'],
 ['Comedy'],
 ['Action', 'Drama', 'Thriller'],
 ['Drama'],
 ['Comedy', 'Drama'],
 ['Drama'],
 ['Romance'],
 ['Crime', 'Drama'],
 ['Drama'],
 ['Action', 'Drama', 'Musical'],
 ['Drama'],
 ['Adventure', 'Mystery', 'Thriller'],
 ['Action', 'Crime', 'Drama'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama'],
 ['Action', 'Drama', 'Romance'],
 ['Action', 'Adventure', 'Drama'],
 ['Action', 'Comedy', 'Crime'],
 ['Action', 'Crime', 'Drama'],
 ['Drama'],
 ['Romance'],
 ['Comedy', 'Drama'],
 ['Drama', 'Romance'],
 ['Romance'],
 ['Drama', 'Romance'],
 ['Romance'],
 ['Action', 'Crime', 'Drama'],
 ['Documentary'],
 ['Action', 'Adventure', 'Comedy'],
 ['Action', 'Comedy', 'Drama'],
 ['Action', 'Drama'],
 ['Drama'],
 ['Biography', 'Drama', 'Sport'],
 ['Drama'],
 ['Crime', 'Drama', 'Thriller'],
 ['Drama'],
 ['Drama', 'Romance'],
 ['Action', 'Comedy', 'Crime'],
 ['Action', 'Crime', 'Drama'],
 ['Drama', 'Family', 'Romance'],
 ['Action', 'Comedy', 'Crime'],
 ['Action', 'Adventure', 'Thriller'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Romance', 'Thriller'],
 ['Action', 'Thriller'],
 ['Action', 'Comedy', 'Musical'],
 ['Action', 'Drama', 'Romance'],
 ['Family'],
 ['Drama'],
 ['Comedy'],
 ['Comedy'],
 ['Action', 'Comedy', 'Crime'],
 ['Comedy', 'Drama', 'Family'],
 ['Action', 'Comedy', 'Drama'],
 ['Comedy', 'Romance'],
 ['Crime', 'Drama', 'Romance'],
 ['Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Comedy'],
 ['Comedy', 'Romance'],
 ['Mystery', 'Romance', 'Thriller'],
 ['Action', 'Adventure', 'Musical'],
 ['Mystery', 'Thriller'],
 ['Crime', 'Drama', 'Thriller'],
 ['Crime', 'Drama', 'Musical'],
 ['Crime', 'Musical', 'Mystery'],
 ['Action'],
 ['Action', 'Thriller', 'Crime'],
 ['Crime', 'Drama', 'Musical'],
 ['Adventure', 'Comedy', 'Crime'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama', 'Family'],
 ['Drama'],
 ['Drama'],
 ['Drama', 'Sci-Fi'],
 ['Action', 'Crime', 'Thriller'],
 ['Action', 'Thriller'],
 ['Comedy', 'Horror', 'Musical'],
 ['Comedy', 'Drama', 'Romance'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Comedy', 'Crime'],
 ['Drama'],
 ['Family', 'Thriller'],
 ['Thriller'],
 ['Comedy', 'Crime', 'Drama'],
 ['Action', 'Comedy', 'Crime'],
 ['Action', 'Romance'],
 ['Action', 'Adventure', 'Musical'],
 ['Action', 'Crime', 'Drama'],
 ['Drama', 'Romance'],
 ['Drama', 'Action', 'Crime'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama'],
 ['Action', 'Comedy', 'Musical'],
 ['Comedy', 'Drama'],
 ['Comedy', 'Drama', 'Musical'],
 ['Drama'],
 ['Drama', 'Family'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama', 'War'],
 ['Drama'],
 ['Thriller'],
 ['Crime', 'Drama', 'Mystery'],
 ['Action', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Drama'],
 ['Action', 'Drama'],
 ['Comedy', 'Crime', 'Drama'],
 ['Action'],
 ['Comedy', 'Drama'],
 ['Comedy', 'Romance'],
 ['Comedy'],
 ['Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama'],
 ['Drama'],
 ['Action', 'Romance'],
 ['Drama'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Family'],
 ['Drama'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Mystery'],
 ['Comedy'],
 ['Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama', 'Family'],
 ['Drama'],
 ['Drama'],
 ['Adventure', 'Drama', 'Fantasy'],
 ['Comedy', 'Crime', 'Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Family'],
 ['Comedy', 'Drama', 'Thriller'],
 ['Action', 'Drama', 'History'],
 ['Fantasy'],
 ['Action', 'Adventure', 'Comedy'],
 ['Action', 'Drama'],
 ['Animation'],
 ['Animation'],
 ['Comedy'],
 ['Action', 'Thriller'],
 ['Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama'],
 ['Comedy'],
 ['Fantasy'],
 ['Action', 'Adventure'],
 ['Comedy'],
 ['Crime', 'Drama', 'Romance'],
 ['Romance'],
 ['Musical', 'Drama'],
 ['Drama'],
 ['Comedy'],
 ['Drama', 'Thriller'],
 ['Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Drama', 'Horror'],
 ['Action', 'Drama', 'Romance'],
 ['Drama', 'Family', 'Musical'],
 ['Drama', 'Family'],
 ['Action', 'Thriller'],
 ['Family'],
 ['Drama', 'Family'],
 ['Drama', 'Musical', 'Romance'],
 ['Comedy', 'Drama', 'Musical'],
 ['Action', 'Crime', 'Drama'],
 ['Biography', 'Crime', 'Drama'],
 ['Crime', 'Thriller'],
 ['Action', 'Adventure', 'Comedy'],
 ['Comedy', 'Drama'],
 ['Drama', 'Romance'],
 ['Action', 'Drama', 'Music'],
 ['Action', 'Comedy', 'Crime'],
 ['Drama'],
 ['Drama'],
 ['Musical', 'Romance'],
 ['Comedy', 'Crime', 'Drama'],
 ['Drama', 'Romance'],
 ['Action', 'Drama', 'Thriller'],
 ['Adventure', 'Drama', 'Family'],
 ['Comedy', 'Drama', 'Romance'],
 ['Romance'],
 ['Drama', 'Romance'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Mystery', 'Thriller'],
 ['Drama', 'Romance', 'Musical'],
 ['Action', 'Romance'],
 ['Romance', 'Thriller'],
 ['Drama', 'Musical', 'Romance'],
 ['Musical'],
 ['Drama', 'Romance', 'Thriller'],
 ['Drama', 'Romance', 'Thriller'],
 ['Drama', 'Musical'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama', 'Family'],
 ['Action', 'Crime', 'Drama'],
 ['Comedy', 'Romance'],
 ['War'],
 ['Drama'],
 ['Action', 'Drama'],
 ['Drama'],
 ['Comedy', 'Musical', 'Drama'],
 ['Drama', 'Romance'],
 ['Drama', 'Family'],
 ['Drama', 'Family'],
 ['Drama'],
 ['Comedy', 'Crime', 'Drama'],
 ['Action', 'Drama', 'Romance'],
 ['Action', 'Crime'],
 ['Drama'],
 ['Thriller', 'Musical', 'Mystery'],
 ['Horror', 'Mystery'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Drama', 'History'],
 ['Comedy'],
 ['Drama'],
 ['Drama', 'Romance', 'Thriller'],
 ['Drama', 'Family'],
 ['Drama', 'Romance'],
 ['Action', 'Crime', 'Drama'],
 ['Drama', 'Family'],
 ['Drama', 'Mystery', 'Thriller'],
 ['Drama', 'Action', 'Horror'],
 ['Drama', 'Romance'],
 ['Action', 'Crime'],
 ['Comedy', 'Drama'],
 ['Drama', 'Family'],
 ['Action', 'Crime', 'Thriller'],
 ['Adventure', 'Crime', 'Drama'],
 ['Action', 'Drama'],
 ['Action', 'Comedy', 'Romance'],
 ['Drama', 'Romance'],
 ['Family', 'Romance'],
 ['Drama', 'Romance'],
 ['Action', 'Drama'],
 ['Drama'],
 ['Comedy', 'Drama', 'Family'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Romance'],
 ['Thriller'],
 ['Comedy', 'Drama', 'Romance'],
 ['Musical'],
 ['Crime', 'Fantasy', 'Mystery'],
 ['Documentary', 'Biography', 'Drama'],
 ['Drama', 'Family'],
 ['Drama', 'Romance'],
 ['Musical', 'Romance'],
 ['Action', 'Fantasy', 'Thriller'],
 ['Biography', 'Drama', 'Sport'],
 ['Comedy'],
 ['Comedy', 'Drama', 'Family'],
 ['Drama'],
 ['Drama', 'Family'],
 ['Comedy', 'Romance'],
 ['Thriller'],
 ['Action', 'Comedy', 'Crime'],

In [37]:
df_encoded

,Action,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,Fantasy,...,Music,Musical,Mystery,News,Romance,Sci-Fi,Sport,Thriller,War,Western
0,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,True,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,True,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5654,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
5655,False,False,False,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
5656,True,False,False,False,False,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
5657,True,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
5658,True,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [38]:
df = pd.read_csv(r"C:\Users\dell\Downloads\movies_data.csv").dropna()
df.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,#Gadhvi (He thought he was Gandhi),2019,109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
1,#Yaaram,2019,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
2,...Aur Pyaar Ho Gaya,1997,147,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
3,...Yahaan,2005,142,"Drama, Romance, War",7.4,1086,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
4,?: A Question Mark,2012,82,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia

In [43]:
transactions = df['Genre'].str.split(r'\s*,\s*').tolist()

te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df_encoded = pd.DataFrame(te_ary,columns=te.columns_)
df_encoded

,Action,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,Fantasy,...,Music,Musical,Mystery,News,Romance,Sci-Fi,Sport,Thriller,War,Western
0,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,True,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,True,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5654,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
5655,False,False,False,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
5656,True,False,False,False,False,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
5657,True,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
5658,True,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [42]:
transactions

[['Drama'],
 ['Comedy', 'Romance'],
 ['Comedy', 'Drama', 'Musical'],
 ['Drama', 'Romance', 'War'],
 ['Horror', 'Mystery', 'Thriller'],
 ['Action', 'Crime', 'Thriller'],
 ['Drama'],
 ['Horror'],
 ['Horror', 'Romance', 'Thriller'],
 ['Comedy', 'Drama', 'Romance'],
 ['Comedy', 'Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Crime', 'Drama', 'Mystery'],
 ['Horror', 'Thriller'],
 ['Comedy', 'Horror'],
 ['Drama', 'Horror', 'Mystery'],
 ['Drama'],
 ['Drama'],
 ['Action', 'Thriller'],
 ['Action'],
 ['Drama'],
 ['Horror', 'Mystery', 'Romance'],
 ['Horror', 'Mystery'],
 ['Drama', 'Horror', 'Romance'],
 ['Horror', 'Mystery', 'Romance'],
 ['Action', 'Drama', 'History'],
 ['Action', 'Drama', 'War'],
 ['Thriller'],
 ['Comedy'],
 ['Adventure', 'Horror', 'Mystery'],
 ['Action', 'Crime', 'Thriller'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Sci-Fi'],
 ['Crime', 'Mystery', 'Thriller'],
 ['Comedy'],
 ['Thriller'],
 ['Drama', 'History'],
 ['Sport'],
 ['Biography', 'Drama', 'History'],
 ['Drama'],
 ['Horror', 'Romance'],
 ['Comedy', 'Romance'],
 ['Crime', 'Drama'],
 ['Comedy'],
 ['Comedy', 'Drama'],
 ['Drama'],
 ['Adventure', 'Drama'],
 ['Action', 'Drama', 'History'],
 ['Comedy', 'Mystery', 'Thriller'],
 ['Drama', 'Romance'],
 ['Crime', 'Thriller'],
 ['Drama'],
 ['Horror'],
 ['Horror', 'Sci-Fi', 'Thriller'],
 ['Horror'],
 ['Drama', 'Mystery', 'Thriller'],
 ['Drama'],
 ['Drama', 'Family', 'Musical'],
 ['Thriller'],
 ['Action', 'Comedy'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Horror'],
 ['Drama'],
 ['Comedy', 'Drama'],
 ['Action'],
 ['Crime', 'Thriller'],
 ['Documentary'],
 ['Drama', 'Mystery', 'Thriller'],
 ['Drama', 'Horror', 'Musical'],
 ['Thriller'],
 ['Action', 'Biography', 'Drama'],
 ['Action', 'Fantasy', 'Mystery'],
 ['Adventure', 'Drama', 'Mystery'],
 ['Mystery', 'Thriller'],
 ['Action'],
 ['Comedy', 'Crime', 'Drama'],
 ['Musical', 'Romance'],
 ['Crime', 'Drama'],
 ['Drama'],
 ['Drama'],
 ['Drama', 'Thriller'],
 ['Horror', 'Mystery'],
 ['Drama', 'Horror', 'Romance'],
 ['Action', 'Adventure', 'Comedy'],
 ['Comedy', 'Romance'],
 ['Action', 'Comedy'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Romance'],
 ['Thriller'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Musical', 'Romance', 'Drama'],
 ['Drama'],
 ['Action', 'Sci-Fi', 'Thriller'],
 ['Action', 'Drama', 'Romance'],
 ['Mystery', 'Romance'],
 ['Action'],
 ['Drama'],
 ['Fantasy'],
 ['Comedy', 'Crime', 'Drama'],
 ['Horror'],
 ['Action', 'Crime', 'Drama'],
 ['Action'],
 ['Drama'],
 ['Drama'],
 ['Action', 'Crime', 'Thriller'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Action', 'Crime', 'Drama'],
 ['Fantasy'],
 ['Drama', 'Romance', 'Thriller'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Drama', 'Family'],
 ['Horror'],
 ['Crime', 'Drama'],
 ['Musical', 'Romance'],
 ['Action', 'Comedy', 'Drama'],
 ['Action'],
 ['Action'],
 ['Action', 'Drama'],
 ['Action'],
 ['Action', 'Thriller'],
 ['Action'],
 ['Horror'],
 ['Comedy', 'Crime', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Action', 'Drama'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Drama'],
 ['Drama', 'Romance'],
 ['Action'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Drama'],
 ['Action', 'Thriller'],
 ['Action', 'Romance'],
 ['Action', 'Crime'],
 ['Action', 'Romance'],
 ['Action', 'Drama'],
 ['Action', 'Drama'],
 ['Action'],
 ['Action', 'Drama', 'Crime'],
 ['Romance'],
 ['Drama', 'Family', 'Music'],
 ['Drama', 'Romance'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Thriller'],
 ['Action', 'Drama', 'Family'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Thriller'],
 ['Drama'],
 ['Action', 'Romance'],
 ['Action'],
 ['Drama', 'History', 'Romance'],
 ['Crime', 'Drama', 'Music'],
 ['Action', 'Crime', 'Thriller'],
 ['Sci-Fi'],
 ['Action', 'Thriller'],
 ['Action'],
 ['Drama', 'Family'],
 ['Comedy', 'Drama', 'Family'],
 ['Action', 'Crime', 'Drama'],
 ['Crime', 'Mystery', 'Romance'],
 ['Action', 'Crime', 'Drama'],
 ['Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Action', 'Crime', 'Drama'],
 ['Drama'],
 ['Action', 'Drama', 'Family'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Drama'],
 ['Drama'],
 ['Drama'],
 ['Action', 'Comedy', 'Crime'],
 ['Crime', 'Drama', 'Thriller'],
 ['Drama', 'Romance'],
 ['Comedy', 'Drama', 'Family'],
 ['Romance'],
 ['Comedy', 'Family', 'Fantasy'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama', 'Family'],
 ['Romance', 'Drama'],
 ['Action', 'Comedy', 'Drama'],
 ['Comedy', 'Romance'],
 ['Drama', 'Family', 'Romance'],
 ['Action', 'Drama', 'Romance'],
 ['Romance', 'Drama', 'Family'],
 ['Action', 'Romance'],
 ['Action', 'Comedy', 'Drama'],
 ['Action'],
 ['Thriller'],
 ['Drama', 'Thriller'],
 ['Drama'],
 ['Musical', 'Romance', 'Thriller'],
 ['Family', 'Musical', 'Romance'],
 ['Action', 'Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Comedy', 'Romance'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama'],
 ['Romance'],
 ['Action', 'Drama', 'Romance'],
 ['Drama', 'Romance', 'Thriller'],
 ['Romance'],
 ['Musical', 'Drama', 'Romance'],
 ['Drama', 'Music', 'Musical'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Drama'],
 ['Drama', 'Mystery'],
 ['Drama'],
 ['Adventure', 'Comedy', 'Romance'],
 ['Action'],
 ['Drama', 'Family'],
 ['Drama'],
 ['Action', 'Thriller'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Drama', 'Thriller'],
 ['Action'],
 ['Action', 'Crime', 'Drama'],
 ['Crime', 'Drama', 'Horror'],
 ['Drama', 'Horror', 'Thriller'],
 ['Comedy', 'Romance'],
 ['Drama', 'Romance'],
 ['Romance'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Action'],
 ['Musical', 'Romance'],
 ['Action', 'Musical', 'Thriller'],
 ['Action', 'Drama', 'Romance'],
 ['Comedy'],
 ['Drama'],
 ['Comedy'],
 ['Action', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Crime', 'Thriller'],
 ['Drama', 'Romance'],
 ['Action', 'Drama', 'War'],
 ['Romance', 'Thriller'],
 ['Drama', 'Music'],
 ['Action', 'Drama', 'Romance'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Fantasy'],
 ['Action', 'Drama', 'Thriller'],
 ['Drama', 'Romance'],
 ['Drama', 'Musical'],
 ['Crime', 'Drama', 'Musical'],
 ['Action', 'Comedy', 'Drama'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Crime', 'Drama', 'Thriller'],
 ['Crime', 'Drama'],
 ['Action', 'Mystery', 'Thriller'],
 ['Drama', 'Musical', 'Romance'],
 ['Action', 'Crime', 'Mystery'],
 ['Action', 'Adventure', 'Thriller'],
 ['Action', 'Crime', 'Thriller'],
 ['Comedy', 'Romance', 'Sci-Fi'],
 ['Action', 'Crime', 'Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Action', 'Drama', 'Family'],
 ['Action', 'Drama', 'Mystery'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Drama'],
 ['Drama'],
 ['Action', 'Comedy', 'Thriller'],
 ['Biography', 'Drama'],
 ['Drama'],
 ['Action', 'Comedy', 'Fantasy'],
 ['Drama', 'Family', 'Horror'],
 ['Drama'],
 ['Adventure'],
 ['Adventure'],
 ['Action', 'Adventure', 'Family'],
 ['Action', 'Adventure', 'Comedy'],
 ['Drama', 'Music', 'Musical'],
 ['Action', 'Drama', 'Musical'],
 ['Action', 'Comedy', 'Crime'],
 ['Adventure', 'Thriller'],
 ['Drama', 'Romance'],
 ['Drama', 'Family'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Comedy', 'Romance'],
 ['Crime', 'Mystery'],
 ['Drama', 'Family'],
 ['Adventure', 'Comedy', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Adventure', 'Thriller'],
 ['Drama', 'Crime'],
 ['Action', 'Drama', 'Romance'],
 ['Action'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action'],
 ['Crime', 'Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Action'],
 ['Action'],
 ['Drama', 'Fantasy', 'Romance'],
 ['Musical', 'Comedy', 'Drama'],
 ['Drama', 'Horror', 'Mystery'],
 ['Comedy', 'Drama'],
 ['Drama'],
 ['Action', 'Drama'],
 ['Musical', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama', 'History'],
 ['Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Comedy', 'Romance'],
 ['Action', 'Comedy', 'Drama'],
 ['Romance', 'Thriller'],
 ['Drama', 'Romance', 'Thriller'],
 ['Action', 'Drama', 'Thriller'],
 ['Comedy', 'Romance'],
 ['Comedy', 'Romance'],
 ['Action', 'Comedy', 'Romance'],
 ['Drama'],
 ['Drama', 'Romance'],
 ['Action', 'Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Adventure', 'Comedy'],
 ['Action', 'Thriller'],
 ['Action', 'Comedy', 'Crime'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Action', 'Drama', 'Thriller'],
 ['Drama', 'History', 'Musical'],
 ['Thriller'],
 ['Drama'],
 ['Romance'],
 ['Comedy', 'Romance'],
 ['Action', 'Drama'],
 ['Action', 'Crime', 'Horror'],
 ['Drama', 'Romance', 'Thriller'],
 ['Crime', 'Drama', 'Mystery'],
 ['Drama', 'Musical'],
 ['Adventure', 'Fantasy'],
 ['Action', 'Adventure', 'Comedy'],
 ['Family', 'Musical', 'Romance'],
 ['Action', 'Drama', 'Fantasy'],
 ['Comedy'],
 ['Drama'],
 ['Adventure', 'Drama', 'Fantasy'],
 ['Comedy', 'Drama', 'Romance'],
 ['Comedy', 'Drama', 'Musical'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama'],
 ['Drama'],
 ['Adventure', 'Fantasy', 'Romance'],
 ['Action', 'Adventure', 'Drama'],
 ['Action', 'Adventure'],
 ['Drama'],
 ['Fantasy'],
 ['Biography', 'Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Thriller'],
 ['Action', 'Drama'],
 ['Action', 'Comedy', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Comedy'],
 ['Action', 'Drama'],
 ['Horror'],
 ['Comedy', 'Crime', 'Drama'],
 ['Action', 'Drama'],
 ['Adventure', 'Drama', 'Romance'],
 ['Action'],
 ['Drama', 'Family'],
 ['Drama', 'Musical', 'Romance'],
 ['Musical', 'Romance'],
 ['Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama'],
 ['Drama'],
 ['Action', 'Adventure', 'Comedy'],
 ['Action', 'Comedy', 'Drama'],
 ['Horror', 'Thriller'],
 ['Family'],
 ['Action', 'Adventure', 'Drama'],
 ['Mystery'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Thriller'],
 ['Family'],
 ['Comedy', 'Romance'],
 ['Drama'],
 ['Drama', 'Fantasy', 'Thriller'],
 ['Comedy', 'Drama'],
 ['Musical', 'Fantasy'],
 ['Drama', 'Family'],
 ['Drama'],
 ['Musical', 'Romance', 'Thriller'],
 ['Documentary', 'Thriller'],
 ['Drama'],
 ['Mystery', 'Romance', 'Musical'],
 ['Drama', 'Musical'],
 ['Biography', 'Drama', 'History'],
 ['Drama', 'Family'],
 ['Comedy', 'Drama', 'Musical'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Comedy'],
 ['History', 'Musical', 'Romance'],
 ['Crime', 'Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Musical', 'Drama', 'Crime'],
 ['Drama', 'Romance'],
 ['Action', 'Comedy', 'Drama'],
 ['Action', 'Comedy', 'Romance'],
 ['Action', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Drama'],
 ['Crime', 'Drama', 'Music'],
 ['Crime', 'Drama', 'Thriller'],
 ['Comedy', 'Drama'],
 ['Drama', 'Thriller'],
 ['Action', 'Comedy', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Crime'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Drama'],
 ['Comedy'],
 ['Drama'],
 ['Action', 'Romance'],
 ['Comedy', 'Drama'],
 ['Comedy', 'Drama'],
 ['Action', 'Adventure', 'Drama'],
 ['Drama', 'Romance', 'Thriller'],
 ['Drama', 'Romance', 'Thriller'],
 ['Musical', 'Thriller', 'Mystery'],
 ['Thriller'],
 ['Drama', 'Thriller'],
 ['Romance'],
 ['Comedy', 'Drama', 'Musical'],
 ['Horror'],
 ['Action', 'Comedy', 'Crime'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Comedy', 'Crime'],
 ['Drama'],
 ['Biography', 'Drama', 'Romance'],
 ['Action', 'Adventure', 'Drama'],
 ['Comedy', 'Drama'],
 ['Romance'],
 ['Drama', 'Thriller'],
 ['Drama'],
 ['Action', 'Drama'],
 ['Drama', 'Family', 'Romance'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama'],
 ['Drama', 'Family'],
 ['Biography'],
 ['Drama'],
 ['Action', 'Drama'],
 ['Action', 'Comedy', 'Crime'],
 ['Comedy'],
 ['Drama'],
 ['Drama'],
 ['Drama', 'Family'],
 ['History'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama', 'Romance'],
 ['Crime', 'Drama', 'Mystery'],
 ['Drama', 'Musical', 'Romance'],
 ['Crime', 'Drama', 'Thriller'],
 ['Drama', 'Family'],
 ['Crime', 'Drama'],
 ['Drama'],
 ['Drama'],
 ['Action'],
 ['Mystery', 'Thriller'],
 ['Drama'],
 ['Crime'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama', 'Family'],
 ['Drama', 'Romance', 'Thriller'],
 ['Biography', 'Drama', 'Music'],
 ['Action'],
 ['Action', 'Crime', 'Drama'],
 ['Drama', 'Mystery', 'Thriller'],
 ['Drama', 'Sci-Fi'],
 ['Comedy'],
 ['Comedy', 'Musical', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama', 'Sport'],
 ['Action', 'Drama'],
 ['Crime', 'Drama', 'Mystery'],
 ['Drama', 'Family', 'Comedy'],
 ['Drama', 'Romance'],
 ['Action', 'Thriller', 'Romance'],
 ['Drama'],
 ['Mystery'],
 ['Comedy', 'Romance', 'Thriller'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama'],
 ['Crime', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Crime', 'Musical'],
 ['Action', 'Crime', 'Romance'],
 ['Action', 'Comedy'],
 ['Animation', 'Action', 'Adventure'],
 ['Drama', 'Family'],
 ['Drama', 'Family', 'Romance'],
 ['Action', 'Drama'],
 ['Drama', 'Family', 'Music'],
 ['Comedy', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Crime', 'Drama', 'Mystery'],
 ['Drama'],
 ['Action', 'Drama'],
 ['Action', 'Drama', 'Sport'],
 ['Musical', 'Romance'],
 ['Drama', 'Musical', 'Romance'],
 ['Action', 'Adventure', 'Drama'],
 ['Documentary', 'History'],
 ['Drama', 'Romance'],
 ['Drama', 'Family', 'Romance'],
 ['Action', 'Thriller'],
 ['Drama', 'Romance'],
 ['Thriller'],
 ['Action'],
 ['Drama'],
 ['Action', 'Biography', 'Drama'],
 ['Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama'],
 ['Family'],
 ['Comedy', 'Musical'],
 ['Drama'],
 ['Thriller'],
 ['Action', 'Adventure', 'Comedy'],
 ['Action'],
 ['Crime', 'Drama'],
 ['Drama', 'Romance'],
 ['Comedy'],
 ['Comedy'],
 ['Drama', 'Musical'],
 ['Biography', 'Crime', 'Thriller'],
 ['Comedy', 'Drama'],
 ['Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Horror', 'Mystery', 'Thriller'],
 ['Comedy'],
 ['Action', 'Drama', 'Thriller'],
 ['Drama'],
 ['Comedy', 'Drama'],
 ['Drama'],
 ['Romance'],
 ['Crime', 'Drama'],
 ['Drama'],
 ['Action', 'Drama', 'Musical'],
 ['Drama'],
 ['Adventure', 'Mystery', 'Thriller'],
 ['Action', 'Crime', 'Drama'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama'],
 ['Action', 'Drama', 'Romance'],
 ['Action', 'Adventure', 'Drama'],
 ['Action', 'Comedy', 'Crime'],
 ['Action', 'Crime', 'Drama'],
 ['Drama'],
 ['Romance'],
 ['Comedy', 'Drama'],
 ['Drama', 'Romance'],
 ['Romance'],
 ['Drama', 'Romance'],
 ['Romance'],
 ['Action', 'Crime', 'Drama'],
 ['Documentary'],
 ['Action', 'Adventure', 'Comedy'],
 ['Action', 'Comedy', 'Drama'],
 ['Action', 'Drama'],
 ['Drama'],
 ['Biography', 'Drama', 'Sport'],
 ['Drama'],
 ['Crime', 'Drama', 'Thriller'],
 ['Drama'],
 ['Drama', 'Romance'],
 ['Action', 'Comedy', 'Crime'],
 ['Action', 'Crime', 'Drama'],
 ['Drama', 'Family', 'Romance'],
 ['Action', 'Comedy', 'Crime'],
 ['Action', 'Adventure', 'Thriller'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Romance', 'Thriller'],
 ['Action', 'Thriller'],
 ['Action', 'Comedy', 'Musical'],
 ['Action', 'Drama', 'Romance'],
 ['Family'],
 ['Drama'],
 ['Comedy'],
 ['Comedy'],
 ['Action', 'Comedy', 'Crime'],
 ['Comedy', 'Drama', 'Family'],
 ['Action', 'Comedy', 'Drama'],
 ['Comedy', 'Romance'],
 ['Crime', 'Drama', 'Romance'],
 ['Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Comedy'],
 ['Comedy', 'Romance'],
 ['Mystery', 'Romance', 'Thriller'],
 ['Action', 'Adventure', 'Musical'],
 ['Mystery', 'Thriller'],
 ['Crime', 'Drama', 'Thriller'],
 ['Crime', 'Drama', 'Musical'],
 ['Crime', 'Musical', 'Mystery'],
 ['Action'],
 ['Action', 'Thriller', 'Crime'],
 ['Crime', 'Drama', 'Musical'],
 ['Adventure', 'Comedy', 'Crime'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama', 'Family'],
 ['Drama'],
 ['Drama'],
 ['Drama', 'Sci-Fi'],
 ['Action', 'Crime', 'Thriller'],
 ['Action', 'Thriller'],
 ['Comedy', 'Horror', 'Musical'],
 ['Comedy', 'Drama', 'Romance'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Comedy', 'Crime'],
 ['Drama'],
 ['Family', 'Thriller'],
 ['Thriller'],
 ['Comedy', 'Crime', 'Drama'],
 ['Action', 'Comedy', 'Crime'],
 ['Action', 'Romance'],
 ['Action', 'Adventure', 'Musical'],
 ['Action', 'Crime', 'Drama'],
 ['Drama', 'Romance'],
 ['Drama', 'Action', 'Crime'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama'],
 ['Action', 'Comedy', 'Musical'],
 ['Comedy', 'Drama'],
 ['Comedy', 'Drama', 'Musical'],
 ['Drama'],
 ['Drama', 'Family'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama', 'War'],
 ['Drama'],
 ['Thriller'],
 ['Crime', 'Drama', 'Mystery'],
 ['Action', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Drama'],
 ['Action', 'Drama'],
 ['Comedy', 'Crime', 'Drama'],
 ['Action'],
 ['Comedy', 'Drama'],
 ['Comedy', 'Romance'],
 ['Comedy'],
 ['Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama'],
 ['Drama'],
 ['Action', 'Romance'],
 ['Drama'],
 ['Drama', 'Romance'],
 ['Drama'],
 ['Family'],
 ['Drama'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Mystery'],
 ['Comedy'],
 ['Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama', 'Family'],
 ['Drama'],
 ['Drama'],
 ['Adventure', 'Drama', 'Fantasy'],
 ['Comedy', 'Crime', 'Drama'],
 ['Drama', 'Musical', 'Romance'],
 ['Family'],
 ['Comedy', 'Drama', 'Thriller'],
 ['Action', 'Drama', 'History'],
 ['Fantasy'],
 ['Action', 'Adventure', 'Comedy'],
 ['Action', 'Drama'],
 ['Animation'],
 ['Animation'],
 ['Comedy'],
 ['Action', 'Thriller'],
 ['Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama'],
 ['Comedy'],
 ['Fantasy'],
 ['Action', 'Adventure'],
 ['Comedy'],
 ['Crime', 'Drama', 'Romance'],
 ['Romance'],
 ['Musical', 'Drama'],
 ['Drama'],
 ['Comedy'],
 ['Drama', 'Thriller'],
 ['Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Drama', 'Horror'],
 ['Action', 'Drama', 'Romance'],
 ['Drama', 'Family', 'Musical'],
 ['Drama', 'Family'],
 ['Action', 'Thriller'],
 ['Family'],
 ['Drama', 'Family'],
 ['Drama', 'Musical', 'Romance'],
 ['Comedy', 'Drama', 'Musical'],
 ['Action', 'Crime', 'Drama'],
 ['Biography', 'Crime', 'Drama'],
 ['Crime', 'Thriller'],
 ['Action', 'Adventure', 'Comedy'],
 ['Comedy', 'Drama'],
 ['Drama', 'Romance'],
 ['Action', 'Drama', 'Music'],
 ['Action', 'Comedy', 'Crime'],
 ['Drama'],
 ['Drama'],
 ['Musical', 'Romance'],
 ['Comedy', 'Crime', 'Drama'],
 ['Drama', 'Romance'],
 ['Action', 'Drama', 'Thriller'],
 ['Adventure', 'Drama', 'Family'],
 ['Comedy', 'Drama', 'Romance'],
 ['Romance'],
 ['Drama', 'Romance'],
 ['Action', 'Crime', 'Drama'],
 ['Action', 'Crime', 'Drama'],
 ['Mystery', 'Thriller'],
 ['Drama', 'Romance', 'Musical'],
 ['Action', 'Romance'],
 ['Romance', 'Thriller'],
 ['Drama', 'Musical', 'Romance'],
 ['Musical'],
 ['Drama', 'Romance', 'Thriller'],
 ['Drama', 'Romance', 'Thriller'],
 ['Drama', 'Musical'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama', 'Musical', 'Romance'],
 ['Drama', 'Family'],
 ['Action', 'Crime', 'Drama'],
 ['Comedy', 'Romance'],
 ['War'],
 ['Drama'],
 ['Action', 'Drama'],
 ['Drama'],
 ['Comedy', 'Musical', 'Drama'],
 ['Drama', 'Romance'],
 ['Drama', 'Family'],
 ['Drama', 'Family'],
 ['Drama'],
 ['Comedy', 'Crime', 'Drama'],
 ['Action', 'Drama', 'Romance'],
 ['Action', 'Crime'],
 ['Drama'],
 ['Thriller', 'Musical', 'Mystery'],
 ['Horror', 'Mystery'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Drama', 'History'],
 ['Comedy'],
 ['Drama'],
 ['Drama', 'Romance', 'Thriller'],
 ['Drama', 'Family'],
 ['Drama', 'Romance'],
 ['Action', 'Crime', 'Drama'],
 ['Drama', 'Family'],
 ['Drama', 'Mystery', 'Thriller'],
 ['Drama', 'Action', 'Horror'],
 ['Drama', 'Romance'],
 ['Action', 'Crime'],
 ['Comedy', 'Drama'],
 ['Drama', 'Family'],
 ['Action', 'Crime', 'Thriller'],
 ['Adventure', 'Crime', 'Drama'],
 ['Action', 'Drama'],
 ['Action', 'Comedy', 'Romance'],
 ['Drama', 'Romance'],
 ['Family', 'Romance'],
 ['Drama', 'Romance'],
 ['Action', 'Drama'],
 ['Drama'],
 ['Comedy', 'Drama', 'Family'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Romance'],
 ['Thriller'],
 ['Comedy', 'Drama', 'Romance'],
 ['Musical'],
 ['Crime', 'Fantasy', 'Mystery'],
 ['Documentary', 'Biography', 'Drama'],
 ['Drama', 'Family'],
 ['Drama', 'Romance'],
 ['Musical', 'Romance'],
 ['Action', 'Fantasy', 'Thriller'],
 ['Biography', 'Drama', 'Sport'],
 ['Comedy'],
 ['Comedy', 'Drama', 'Family'],
 ['Drama'],
 ['Drama', 'Family'],
 ['Comedy', 'Romance'],
 ['Thriller'],
 ['Action', 'Comedy', 'Crime'],

In [45]:
frequent_itemsets = apriori(df_encoded, min_support=0.02, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.2)

# 5. Top rules display karein
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,support,confidence,lift
23,frozenset({Crime}),"frozenset({Action, Drama})",0.058844,0.380571,2.168836
22,"frozenset({Action, Drama})",frozenset({Crime}),0.058844,0.335347,2.168836
0,frozenset({Adventure}),frozenset({Action}),0.028980,0.592058,1.987221
3,frozenset({Action}),frozenset({Crime}),0.090299,0.303084,1.960176
2,frozenset({Crime}),frozenset({Action}),0.090299,0.584000,1.960176
18,frozenset({Musical}),frozenset({Romance}),0.034105,0.468447,1.920971
21,"frozenset({Crime, Drama})",frozenset({Action}),0.058844,0.568259,1.907343
11,frozenset({Thriller}),frozenset({Crime}),0.025800,0.215022,1.390640
12,frozenset({Family}),frozenset({Drama}),0.058844,0.800481,1.193341
9,frozenset({Romance}),frozenset({Comedy}),0.065383,0.268116,1.128920

In [56]:
# Matrix ko movie names ke sath DataFrame banayein
# (Duplicates handle karne ke liye reset_index zaroori hai)
df = df.reset_index(drop=True)
indices = pd.Series(df.index, index=df['Name']).drop_duplicates()

def get_recommendations(title, top_n=5):
    if title not in indices:
        return f"'{title}' dataset me nahi hai!"
    
    # Movie ka index nikaalo
    idx = indices[title]
    
    # Us movie ke saare similarity scores nikaalo
    sim_scores = list(enumerate(sim_matrix[idx]))
    
    # Scores ko descending order me sort karo
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    
    # Top similar movies (0th index movie khud hoti hai, isliye 1 se slice)
    movie_indices = [i[0] for i in sim_scores[1:top_n+1]]
    
    return df[['Name', 'Genre', 'Director', 'Actor 1']].iloc[movie_indices]

# Test karke dekhein:
get_recommendations('#Yaaram', top_n=10)

,Name,Genre,Director,Actor 1
1755,Firangi,"Comedy, Drama",Rajiv Dhingra,Kapil Sharma
2353,Issaq,"Drama, Romance",Manish Tiwary,Prateik
1408,Dhobi Ghat,Drama,Kiran Rao,Prateik
1867,Genius,"Action, Thriller",Anil Sharma,Utkarsh Sharma
3622,My Friend Pinto,"Comedy, Crime, Drama",Raaghav Dar,Prateik
248,Abdullah,"Action, Drama, Romance",Sanjay Khan,Raj Kapoor
1690,Ekk Deewana Tha,"Drama, Romance",Gautham Vasudev Menon,Prateik
3404,Mera Naam Joker,"Comedy, Drama",Raj Kapoor,Raj Kapoor
4747,Shree 420,"Comedy, Crime, Drama",Raj Kapoor,Nargis
571,Awaara,"Drama, Musical, Romance",Raj Kapoor,Raj Kapoor

In [59]:
# Yeh direct original df ke columns use kar raha hai:
df['combined_features'] = df['Genre'] + " " + df['Director'] + " " + df['Actor 1'] + " " + df['Actor 2']

# Phir TF-IDF laga kar sim_matrix banaya gaya:
tfidf_matrix = tfidf.fit_transform(df['combined_features'].fillna(''))
sim_matrix = cosine_similarity(tfidf_matrix, tfidf_matrix)
get_recommendations('#Yaaram', top_n=5)

                 Name                 Genre       Director         Actor 1
1755          Firangi         Comedy, Drama  Rajiv Dhingra    Kapil Sharma
2353            Issaq        Drama, Romance  Manish Tiwary         Prateik
1408       Dhobi Ghat                 Drama      Kiran Rao         Prateik
1867           Genius      Action, Thriller    Anil Sharma  Utkarsh Sharma
3622  My Friend Pinto  Comedy, Crime, Drama    Raaghav Dar         Prateik

In [60]:
df.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,combined_features
0,#Gadhvi (He thought he was Gandhi),2019,109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,Drama Gaurav Bakshi Rasika Dugal Vivek Ghamande
1,#Yaaram,2019,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor,"Comedy, Romance Ovais Khan Prateik Ishita Raj"
2,...Aur Pyaar Ho Gaya,1997,147,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor,"Comedy, Drama, Musical Rahul Rawail Bobby Deol..."
3,...Yahaan,2005,142,"Drama, Romance, War",7.4,1086,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma,"Drama, Romance, War Shoojit Sircar Jimmy Sheir..."
4,?: A Question Mark,2012,82,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia,"Horror, Mystery, Thriller Allyson Patel Yash D..."