In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Empid':[x for x in range(101,116)],
    'Empname':['Raj','Raman','Rahul','Anu','Manu','Aman','Sonu','Shiva','Ram','Anu','ankur','ankit','ansh','ayush','prince'],
    'Empsalary':[23445,78898,46665,89897,23345,67856,45433,78978,56555,45786,51000,55000,53000,49990,51050]
}

In [4]:
df  = pd.DataFrame(data)

In [5]:
df.head().Empsalary.sum()

np.int64(262250)

In [6]:
df.Empsalary.sum().sum()

np.int64(816898)

In [7]:
df.info

<bound method DataFrame.info of     Empid Empname  Empsalary
0     101     Raj      23445
1     102   Raman      78898
2     103   Rahul      46665
3     104     Anu      89897
4     105    Manu      23345
5     106    Aman      67856
6     107    Sonu      45433
7     108   Shiva      78978
8     109     Ram      56555
9     110     Anu      45786
10    111   ankur      51000
11    112   ankit      55000
12    113    ansh      53000
13    114   ayush      49990
14    115  prince      51050>

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      15 non-null     int64
 1   Empname    15 non-null     str
 2   Empsalary  15 non-null     int64
dtypes: int64(2), str(1)
memory usage: 556.0 bytes

In [9]:
df.describe()

            Empid     Empsalary
count   15.000000     15.000000
mean   108.000000  54459.866667
std      4.472136  18577.127369
min    101.000000  23345.000000
25%    104.500000  46225.500000
50%    108.000000  51050.000000
75%    111.500000  62205.500000
max    115.000000  89897.000000

In [10]:
df.count()

Empid        15
Empname      15
Empsalary    15
dtype: int64

In [11]:
len(df)

15

In [12]:
df['Empid']

0     101
1     102
2     103
3     104
4     105
5     106
6     107
7     108
8     109
9     110
10    111
11    112
12    113
13    114
14    115
Name: Empid, dtype: int64

In [13]:
df.Empsalary

0     23445
1     78898
2     46665
3     89897
4     23345
5     67856
6     45433
7     78978
8     56555
9     45786
10    51000
11    55000
12    53000
13    49990
14    51050
Name: Empsalary, dtype: int64

In [14]:
df.Empname.value_counts()

Empname
Anu       2
Raj       1
Raman     1
Rahul     1
Manu      1
Aman      1
Sonu      1
Shiva     1
Ram       1
ankur     1
ankit     1
ansh      1
ayush     1
prince    1
Name: count, dtype: int64

In [15]:
df.Empsalary.value_counts()

Empsalary
23445    1
78898    1
46665    1
89897    1
23345    1
67856    1
45433    1
78978    1
56555    1
45786    1
51000    1
55000    1
53000    1
49990    1
51050    1
Name: count, dtype: int64

In [16]:
import numpy as np
import pandas as pd
df.Empname.mode()[0]

'Anu'

In [17]:
data = {
    'Empid':[x for x in range(101,118)],
    'Empname':['Raj','Raman','Rahul','Anu','Manu','Aman',np.nan,'Sonu','Shiva','Ram','Anu','ankur','ankit',np.nan,'ansh','ayush','prince'],
    'Empsalary':[23445,78898,46665,89897,23345,67856,45433,np.nan,78978,56555,45786,51000,55000,np.nan,53000,49990,51050]
}

In [18]:
df = pd.DataFrame(data)
df

    Empid Empname  Empsalary
0     101     Raj    23445.0
1     102   Raman    78898.0
2     103   Rahul    46665.0
3     104     Anu    89897.0
4     105    Manu    23345.0
5     106    Aman    67856.0
6     107     NaN    45433.0
7     108    Sonu        NaN
8     109   Shiva    78978.0
9     110     Ram    56555.0
10    111     Anu    45786.0
11    112   ankur    51000.0
12    113   ankit    55000.0
13    114     NaN        NaN
14    115    ansh    53000.0
15    116   ayush    49990.0
16    117  prince    51050.0

In [19]:
df.isnull()

    Empid  Empname  Empsalary
0   False    False      False
1   False    False      False
2   False    False      False
3   False    False      False
4   False    False      False
5   False    False      False
6   False     True      False
7   False    False       True
8   False    False      False
9   False    False      False
10  False    False      False
11  False    False      False
12  False    False      False
13  False     True       True
14  False    False      False
15  False    False      False
16  False    False      False

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      17 non-null     int64
 1   Empname    15 non-null     str
 2   Empsalary  15 non-null     float64
dtypes: float64(1), int64(1), str(1)
memory usage: 607.0 bytes

In [21]:
df.isnull().sum().sum()

np.int64(4)

In [22]:
df.shape

(17, 3)

In [23]:
print("Rows :",df.shape[0])
print("Columns :",df.shape[1])
print("Values :",df.shape[0]*df.shape[1])

Rows : 17
Columns : 3
Values : 51

In [24]:
# missing data in overall dataset
Missing_dataset =(df.isnull().sum().sum()/(df.shape[0]*df.shape[1])*100)
print("Missing_dataset",round(Missing_dataset,2),"%")

Missing_dataset 7.84 %

In [25]:
df.dropna()

    Empid Empname  Empsalary
0     101     Raj    23445.0
1     102   Raman    78898.0
2     103   Rahul    46665.0
3     104     Anu    89897.0
4     105    Manu    23345.0
5     106    Aman    67856.0
8     109   Shiva    78978.0
9     110     Ram    56555.0
10    111     Anu    45786.0
11    112   ankur    51000.0
12    113   ankit    55000.0
14    115    ansh    53000.0
15    116   ayush    49990.0
16    117  prince    51050.0

In [26]:
newdf= df.fillna("not found")
newdf

    Empid    Empname  Empsalary
0     101        Raj    23445.0
1     102      Raman    78898.0
2     103      Rahul    46665.0
3     104        Anu    89897.0
4     105       Manu    23345.0
5     106       Aman    67856.0
6     107  not found    45433.0
7     108       Sonu  not found
8     109      Shiva    78978.0
9     110        Ram    56555.0
10    111        Anu    45786.0
11    112      ankur    51000.0
12    113      ankit    55000.0
13    114  not found  not found
14    115       ansh    53000.0
15    116      ayush    49990.0
16    117     prince    51050.0

In [27]:
newdf.isnull()

    Empid  Empname  Empsalary
0   False    False      False
1   False    False      False
2   False    False      False
3   False    False      False
4   False    False      False
5   False    False      False
6   False    False      False
7   False    False      False
8   False    False      False
9   False    False      False
10  False    False      False
11  False    False      False
12  False    False      False
13  False    False      False
14  False    False      False
15  False    False      False
16  False    False      False

In [28]:
newdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      17 non-null     int64
 1   Empname    17 non-null     str
 2   Empsalary  17 non-null     object
dtypes: int64(1), object(1), str(1)
memory usage: 622.0+ bytes

In [29]:
newdf = df.copy
newdf

<bound method NDFrame.copy of     Empid Empname  Empsalary
0     101     Raj    23445.0
1     102   Raman    78898.0
2     103   Rahul    46665.0
3     104     Anu    89897.0
4     105    Manu    23345.0
5     106    Aman    67856.0
6     107     NaN    45433.0
7     108    Sonu        NaN
8     109   Shiva    78978.0
9     110     Ram    56555.0
10    111     Anu    45786.0
11    112   ankur    51000.0
12    113   ankit    55000.0
13    114     NaN        NaN
14    115    ansh    53000.0
15    116   ayush    49990.0
16    117  prince    51050.0>

In [30]:
df.Empname=df.Empname.fillna('no Name')
df

    Empid  Empname  Empsalary
0     101      Raj    23445.0
1     102    Raman    78898.0
2     103    Rahul    46665.0
3     104      Anu    89897.0
4     105     Manu    23345.0
5     106     Aman    67856.0
6     107  no Name    45433.0
7     108     Sonu        NaN
8     109    Shiva    78978.0
9     110      Ram    56555.0
10    111      Anu    45786.0
11    112    ankur    51000.0
12    113    ankit    55000.0
13    114  no Name        NaN
14    115     ansh    53000.0
15    116    ayush    49990.0
16    117   prince    51050.0

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      17 non-null     int64
 1   Empname    17 non-null     str
 2   Empsalary  15 non-null     float64
dtypes: float64(1), int64(1), str(1)
memory usage: 618.0 bytes

In [32]:
round(df.Empsalary.mean(),2)

np.float64(54459.87)

In [39]:
df.Empsalary=df.Empsalary.fillna(0)
df

    Empid  Empname  Empsalary
0     101      Raj    23445.0
1     102    Raman    78898.0
2     103    Rahul    46665.0
3     104      Anu    89897.0
4     105     Manu    23345.0
5     106     Aman    67856.0
6     107  no Name    45433.0
7     108     Sonu        0.0
8     109    Shiva    78978.0
9     110      Ram    56555.0
10    111      Anu    45786.0
11    112    ankur    51000.0
12    113    ankit    55000.0
13    114  no Name        0.0
14    115     ansh    53000.0
15    116    ayush    49990.0
16    117   prince    51050.0

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      17 non-null     int64
 1   Empname    17 non-null     str
 2   Empsalary  17 non-null     float64
dtypes: float64(1), int64(1), str(1)
memory usage: 618.0 bytes

In [35]:
df.Empsalary.sum()

np.float64(816898.0)

In [113]:
import numpy as np
import pandas as pd
data = {
    'Empid':[x for x in range(101,118)],
    'Empname':['Raj','Raman','Rahul','Anu','Manu','Aman',np.nan,'Sonu','Shiva','Ram','Anu','ankur','ankit',np.nan,'ansh','ayush','prince'],
    'Empsalary':[23445,78898,46665,89897,23345,67856,45433,np.nan,78978,56555,45786,51000,55000,np.nan,53000,49990,51050]
}
nd = pd.DataFrame(data)
ndf = pd.DataFrame(data)
newdf = pd.DataFrame(data)

In [114]:
newdf.Empsalary = round(newdf.Empsalary.fillna(newdf.Empsalary.mean()))
newdf.Empname = newdf.Empname.fillna("no name")

In [115]:
newdf

    Empid  Empname  Empsalary
0     101      Raj    23445.0
1     102    Raman    78898.0
2     103    Rahul    46665.0
3     104      Anu    89897.0
4     105     Manu    23345.0
5     106     Aman    67856.0
6     107  no name    45433.0
7     108     Sonu    54460.0
8     109    Shiva    78978.0
9     110      Ram    56555.0
10    111      Anu    45786.0
11    112    ankur    51000.0
12    113    ankit    55000.0
13    114  no name    54460.0
14    115     ansh    53000.0
15    116    ayush    49990.0
16    117   prince    51050.0

In [116]:
c = round(newdf.Empsalary.mean())
c

54460

In [117]:
newdf.columns

Index(['Empid', 'Empname', 'Empsalary'], dtype='str')

In [118]:
newdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      17 non-null     int64
 1   Empname    17 non-null     str
 2   Empsalary  17 non-null     float64
dtypes: float64(1), int64(1), str(1)
memory usage: 618.0 bytes

In [119]:
c = round(newdf.describe())
c

       Empid  Empsalary
count   17.0       17.0
mean   109.0    54460.0
std      5.0    17377.0
min    101.0    23345.0
25%    105.0    46665.0
50%    109.0    53000.0
75%    113.0    56555.0
max    117.0    89897.0

In [120]:
ndf.Empsalary = round(ndf.Empsalary.fillna(ndf.Empsalary.mean()))
ndf.Empname= ndf.Empname.fillna("no name")

In [121]:
ndf.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Empid      17 non-null     int64
 1   Empname    17 non-null     str
 2   Empsalary  17 non-null     float64
dtypes: float64(1), int64(1), str(1)
memory usage: 618.0 bytes

In [122]:
ndf

    Empid  Empname  Empsalary
0     101      Raj    23445.0
1     102    Raman    78898.0
2     103    Rahul    46665.0
3     104      Anu    89897.0
4     105     Manu    23345.0
5     106     Aman    67856.0
6     107  no name    45433.0
7     108     Sonu    54460.0
8     109    Shiva    78978.0
9     110      Ram    56555.0
10    111      Anu    45786.0
11    112    ankur    51000.0
12    113    ankit    55000.0
13    114  no name    54460.0
14    115     ansh    53000.0
15    116    ayush    49990.0
16    117   prince    51050.0

In [123]:
ndf.head()

   Empid Empname  Empsalary
0    101     Raj    23445.0
1    102   Raman    78898.0
2    103   Rahul    46665.0
3    104     Anu    89897.0
4    105    Manu    23345.0

In [124]:
ndf.tail()

    Empid  Empname  Empsalary
12    113    ankit    55000.0
13    114  no name    54460.0
14    115     ansh    53000.0
15    116    ayush    49990.0
16    117   prince    51050.0

In [125]:
ndf.columns

Index(['Empid', 'Empname', 'Empsalary'], dtype='str')

In [127]:
for col in nd.columns:
    if nd[col].isnull().sum()>0:
        print(col ,'\t', nd[col].dtype ,'\t', nd[col].isnull().sum())

Empname 	 str 	 2
Empsalary 	 float64 	 2

In [1]:
import pandas as pd
import numpy as np
df = pd.read_excel(r"C:\Users\dell\Downloads\Financial_Sample.xlsx")

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              692 non-null    str
 1   Country              689 non-null    str
 2   Product              692 non-null    str
 3   Discount Band        638 non-null    str
 4   Units Sold           695 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           693 non-null    float64
 7   Gross Sales          695 non-null    float64
 8   Discounts            695 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[us]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    str
 15  Year                 700 non-null    int64
dtypes: datetime64[us](1), float64(7), int64(3), str(5)
memory usage: 113.4 KB

In [14]:

for i in df.select_dtypes(include="str").columns:
    df[i] = df[i].astype("object")

Country
Product
Discount Band
Month Name

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              692 non-null    object
 1   Country              689 non-null    object
 2   Product              692 non-null    object
 3   Discount Band        638 non-null    object
 4   Units Sold           695 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           693 non-null    float64
 7   Gross Sales          695 non-null    float64
 8   Discounts            695 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[us]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    object
 15  Year                 700 non-null    int64
dtypes: datetime64[us](1), float64(7), int64(3), object(5)
memory usage: 87.6+ KB

In [2]:
# 'str' ya string dtype columns ko explicitly 'object' dtype me convert karein
for col in df.columns:
    if df[col].dtype == 'str' or 'string' in str(df[col].dtype):
        df[col] = df[col].astype('object')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              692 non-null    object
 1   Country              689 non-null    object
 2   Product              692 non-null    object
 3   Discount Band        638 non-null    object
 4   Units Sold           695 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           693 non-null    float64
 7   Gross Sales          695 non-null    float64
 8   Discounts            695 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[us]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    object
 15  Year                 700 non-null    int64
dtypes: datetime64[us](1), float64(7), int64(3), object(5)
memory usage: 87.6+ KB

In [4]:
df.Product.unique()

array(['Carretera', 'Montana', 'Paseo', 'Velo', 'VTT', 'Amarilla', nan],
      dtype=object)

In [5]:
df.Product.value_counts()

Product
Paseo        202
Velo         108
VTT          108
Montana       93
Carretera     92
Amarilla      89
Name: count, dtype: int64

In [6]:
df.Segment.unique()

array(['Government', 'Midmarket', 'Channel Partners', 'Enterprise',
       'Small Business', nan], dtype=object)

In [7]:
df.Segment.value_counts()

Segment
Government          294
Midmarket           100
Enterprise          100
Small Business      100
Channel Partners     98
Name: count, dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              692 non-null    object
 1   Country              689 non-null    object
 2   Product              692 non-null    object
 3   Discount Band        638 non-null    object
 4   Units Sold           695 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           693 non-null    float64
 7   Gross Sales          695 non-null    float64
 8   Discounts            695 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[us]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    object
 15  Year                 700 non-null    int64
dtypes: datetime64[us](1), float64(7), int64(3), object(5)
memory usage: 87.6+ KB

In [9]:
df.isnull().sum()

Segment                 8
Country                11
Product                 8
Discount Band          62
Units Sold              5
Manufacturing Price     0
Sale Price              7
Gross Sales             5
Discounts               5
 Sales                  0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

In [10]:
df.columns

Index(['Segment', 'Country', 'Product', 'Discount Band', 'Units Sold',
       'Manufacturing Price', 'Sale Price', 'Gross Sales', 'Discounts',
       ' Sales', 'COGS', 'Profit', 'Date', 'Month Number', 'Month Name',
       'Year'],
      dtype='str')

In [11]:
for col in df.columns:
    print(col)

Segment
Country
Product
Discount Band
Units Sold
Manufacturing Price
Sale Price
Gross Sales
Discounts
 Sales
COGS
Profit
Date
Month Number
Month Name
Year

In [12]:
for col in df.columns:
    if df[col].isnull().sum()>0:
        print(col,'\t',df[col].isnull().sum(),'\t',df[col].dtype)

Segment 	 8 	 object
Country 	 11 	 object
Product 	 8 	 object
Discount Band 	 62 	 object
Units Sold 	 5 	 float64
Sale Price 	 7 	 float64
Gross Sales 	 5 	 float64
Discounts 	 5 	 float64

In [13]:
# fill missing values numerical with mean(average) and categorical/text with mode(most_frequent)
for col in df.columns:
    if df[col].isnull().sum()>0:
        if df[col].dtype in [object , str]:
            print(col ,'\t', df[col].isnull().sum() ,'\t', df[col].dtype,'\t Mode : ',df[col].mode()[0])
            df[col] = df[col].fillna( df[col].mode()[0] )
        else:
            print(col ,'\t', df[col].isnull().sum() ,'\t', df[col].dtype , '\t Mean : ' , round(df[col].mean(),2))
            df[col] = df[col].fillna( round(df[col].mean(),2) )

Segment 	 8 	 object 	 Mode :  Government
Country 	 11 	 object 	 Mode :  France
Product 	 8 	 object 	 Mode :  Paseo
Discount Band 	 62 	 object 	 Mode :  High
Units Sold 	 5 	 float64 	 Mean :  1607.88
Sale Price 	 7 	 float64 	 Mean :  117.91
Gross Sales 	 5 	 float64 	 Mean :  183967.04
Discounts 	 5 	 float64 	 Mean :  13077.16

In [14]:
h.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              692 non-null    str
 1   Country              689 non-null    str
 2   Product              692 non-null    str
 3   Discount Band        638 non-null    str
 4   Units Sold           695 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           693 non-null    float64
 7   Gross Sales          695 non-null    float64
 8   Discounts            695 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[us]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    str
 15  Year                 700 non-null    int64
dtypes: datetime64[us](1), float64(7), int64(3), str(5)
memory usage: 113.4 KB

In [15]:
# fill missing values numerical with mean(average) and categorical/text with mode(most_frequent)
for col in h.columns:
    if h[col].isnull().sum()>0:
        if h[col].dtype in ['str','object' , 'string']:# or 'string' in str(h[col].dtype):
            print(col ,'\t', h[col].isnull().sum() ,'\t', h[col].dtype,'\t Mode : ',h[col].mode()[0])
            h[col] = h[col].fillna( h[col].mode()[0] )
        else:
            print(col ,'\t', h[col].isnull().sum() ,'\t', h[col].dtype , '\t Mean : ' , round(h[col].mean(),2))
            h[col] = h[col].fillna( round(h[col].mean(),2) )

Segment 	 8 	 str 	 Mode :  Government
Country 	 11 	 str 	 Mode :  France
Product 	 8 	 str 	 Mode :  Paseo
Discount Band 	 62 	 str 	 Mode :  High
Units Sold 	 5 	 float64 	 Mean :  1607.88
Sale Price 	 7 	 float64 	 Mean :  117.91
Gross Sales 	 5 	 float64 	 Mean :  183967.04
Discounts 	 5 	 float64 	 Mean :  13077.16

In [16]:
df.isnull().sum()==0

Segment                True
Country                True
Product                True
Discount Band          True
Units Sold             True
Manufacturing Price    True
Sale Price             True
Gross Sales            True
Discounts              True
 Sales                 True
COGS                   True
Profit                 True
Date                   True
Month Number           True
Month Name             True
Year                   True
dtype: bool

In [17]:
round(df.describe())

,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Year
count,700.0,700.0,700.0,700.0,700.0,700.0,700.0,700.0,700,700.0,700.0
mean,1608.0,96.0,118.0,183967.0,13077.0,169609.0,145475.0,24134.0,2014-04-28 21:36:00,8.0,2014.0
min,200.0,3.0,7.0,1799.0,0.0,1655.0,918.0,-40618.0,2013-09-01 00:00:00,1.0,2013.0
25%,911.0,5.0,12.0,17625.0,801.0,15928.0,7490.0,2806.0,2013-12-24 06:00:00,6.0,2014.0
50%,1552.0,10.0,20.0,38592.0,2620.0,35540.0,22506.0,9242.0,2014-05-16 12:00:00,9.0,2014.0
75%,2217.0,250.0,300.0,279025.0,15267.0,261078.0,245608.0,22662.0,2014-09-08 12:00:00,10.0,2014.0
max,4492.0,260.0,350.0,1207500.0,149678.0,1159200.0,950625.0,262200.0,2014-12-01 00:00:00,12.0,2014.0
std,864.0,109.0,136.0,253862.0,22911.0,236726.0,203866.0,42761.0,NaN,3.0,0.0

In [19]:
h.info()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    str
 1   Country              700 non-null    str
 2   Product              700 non-null    str
 3   Discount Band        700 non-null    str
 4   Units Sold           700 non-null    float64
 5   Manufacturing Price  700 non-null    int64
 6   Sale Price           700 non-null    float64
 7   Gross Sales          700 non-null    float64
 8   Discounts            700 non-null    float64
 9    Sales               700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               700 non-null    float64
 12  Date                 700 non-null    datetime64[us]
 13  Month Number         700 non-null    int64
 14  Month Name           700 non-null    str
 15  Year                 700 non-null    int64
dtypes: datetime64[us](1), float64(7), int64(3), str(5)
memory usage: 113.5 KB